import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import LenisSmoothScroll from "@/components/LenisSmoothScroll";

const dmMono = Work_Sans({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chit-Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmMono.className} antialiased`}>
        <LenisSmoothScroll>{children}</LenisSmoothScroll>
      </body>
    </html>
  );
}
